routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {

    Route::get('/projects/{project}/uml-builder', 'UMLBuilderController')->name('umlbuilder');
    Route::resource('/projects', 'ProjectController');
    Route::get('/home', 'ProjectController@index')->name('home');

});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Domain\Projects\Entities\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Domain\Projects\Traits\DirectoryBrowserTrait;

class ProjectController extends Controller
{
    use DirectoryBrowserTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $projects = Project::all();
        return view('projects.index', compact('projects'));
    }

    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255'
        ]);

        $project = Project::create($validated);

        return redirect()->route('umlbuilder', $project->id);

    }

    /**
     * Display the specified resource.
     *
     * @param Project $project
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Project $project)
    {
        $files = $this->getDirectoryAsArray('staging/project_' . $project->id . '/');

        return view('projects.show', compact('project', 'files'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    /**
     * @param Project $project
     * @return \Illuminate\Http\JsonResponse
     */
    public function generate(Project $project)
    {
        Artisan::call("scaffold:laravel", ['project_id' => $project->id, '--silent' => true]);

        return response()->json([
            'message' => "Project has been scaffolded!",
            'data' => $this->getDirectoryAsArray('staging/project_' . $project->id . '/')
        ], 200);
    }
}

resources/views/projects/create.blade.php
@extends('master.main')

@section('content')

    <form class="form" action="{{ route('projects.store') }}" method="post">

        @csrf

        <b-form-group
            label="Project Name"
        >
            <input class="form-control" name="name" required>

        </b-form-group>

        <input type="submit" class="btn btn-primary">

    </form>

@endsection

resources/views/projects/index.blade.php
@extends('master.main')

@section('content')

    <div class="col-md-6">
        <div class="card">
            <b-card-header>
                Projects

                <b-button
                    class="btn-sm float-right"
                    variant="primary"
                    href="{{ route('projects.create') }}"
                >
                    Add Project
                </b-button>
            </b-card-header>
            <b-card-body>
                @if($projects->count() > 0)
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Project Name</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($projects as $project)
                        <tr>
                            <td>{{ $project->name }}</td>
                            <td align="right">
                                <b-button
                                    variant="primary"
                                    href="{{ route('projects.show', $project->id) }}"
                                >
                                    Project Overview
                                </b-button>
                            </td>
                        </tr>
                    @endforeach
                </table>
                @else
                    <div class="alert alert-info">

                        <strong>
                            No projects created.
                        </strong>
                        <p>
                            No projects have been created. Add one and it will be listed here.
                        </p>

                    </div>
                @endif

            </b-card-body>
        </div>
    </div>

@endsection

resources/views/projects/show.blade.php
@extends('master.main')

@section('content')
{{--    <link rel="stylesheet" type="text/css" href="/prettify/prettify.css">--}}

    <h2>
        Project Overview: {{ $project->name }}
    </h2>

    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <generate-project-button :project_id="{{$project->id}}"></generate-project-button>
                    <br>
                    <b-button
                        variant="primary"
                        href="{{ route('umlbuilder', $project->id) }}"
                        class="btn-block"
                    >
                        <i class="fa fa-network-wired"></i>
                        UML Builder
                    </b-button>
                </div>
            </div>
        </div>
        <div class="col-9">
            <directory-viewer-component
                :files="{{json_encode($files)}}"
            />
        </div>
    </div>

@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
@endpush