routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {

    Route::get('/projects/{project}/uml-builder', 'UMLBuilderController')->name('umlbuilder');
    Route::resource('/projects', 'ProjectController');
    Route::get('/home', 'ProjectController@index')->name('home');

});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

resources/views/master/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Scaffold</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    <meta name="theme-color" content="#563d7c">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        .container {
            padding-top: 60px
        }
    </style>
</head>

resources/views/master/_header.blade.php
<header>
    <div>
        <b-navbar toggleable="lg" type="dark" variant="dark">
            <b-navbar-brand href="#">Scaffold App</b-navbar-brand>

            <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

            <b-collapse id="nav-collapse" is-nav>
                <b-navbar-nav>
                    <b-nav-item href="{{route('projects.create')}}">New Project</b-nav-item>

                    <b-nav-item-dropdown text="Projects" left>
                        @foreach(\App\Domain\Projects\Entities\Project::all() as $project)
                            <b-dropdown-item href="{{route('projects.show', $project->id)}}">{{$project->name}}</b-dropdown-item>
                        @endforeach
                    </b-nav-item-dropdown>
                </b-navbar-nav>

                <!-- Right aligned nav items -->
                <b-navbar-nav class="ml-auto">
                    <b-nav-item-dropdown right>
                        <!-- Using 'button-content' slot -->
                        <template v-slot:button-content>
                            <em>{{ \Illuminate\Support\Facades\Auth::user()->name }}</em>
                        </template>
                        <b-dropdown-item href="{{ route('logout') }}">Sign Out</b-dropdown-item>
                    </b-nav-item-dropdown>
                </b-navbar-nav>
            </b-collapse>
        </b-navbar>
    </div>
</header>

resources/views/master/main.blade.php
<!doctype html>
<html lang="en" class="h-100">
@include('master._head')

<body class="d-flex flex-column h-100">
<div id="app">

@include('master._header')

<!-- Begin page content -->
    <main role="main" class="flex-shrink-0">
        <div class="container-fluid pt-4">

            @yield('content')

        </div>
    </main>

</div>
@routes
<script src="{{ mix('/js/app.js') }}"></script>
@stack('scripts')
</body>
</html>